### ISSUE TITLE
Join game through quick scan

### ISSUE THREAD

**Issue by aesedepece** [otherplane/witmon#11]
## User story

As a potential WittyCreatures player, I want to be able to start playing by scanning the QR code printed on my egg without having to navigate first to the webapp, but rather by simply pointing at the egg with my phone's camera app or QR code reader.

## Tentative solution

- The QR codes will contain an URL like https://wittycreatures.com/egg/ef12efbd765f9ad3
- The `/egg/ef12efbd765f9ad3` route **in the UI package** must bring you to the welcome screen / FTU, but should instantly store the egg key.
- If going through the FTU in this way, the egg can set up immediately without prompting the user for scanning the code.

## Extra mile solution

- This could also be extended for incubation. As a player, I would find it specially convenient if I incubate someone's egg by just scanning their QR code from my camera app, without having to manually open the webapp and pressing on incubate.

**Comment by Tommytrg** [comment]
This issues is already fixed
